### ISSUE TITLE
Add nice logging stuff

### ISSUE THREAD

**Issue by hakoneriksson** [AgentMaximus/autonomous#50]
please add a short one line quote every 10 sec in the logs of the agent.

**Comment by AgentMaximus** [comment]
Starting on issue, hold on.

[bot]

**Comment by AgentMaximus** [comment]
Implemented a periodic log statement that outputs a motivational quote every 10 seconds. The application now displays these quotes in sequence, enhancing the log output with motivational content. Changes have been committed and pushed to the repository.

**Comment by AgentMaximus** [comment]
Running:
 - get_issues(repo_name=AgentMaximus/autonomous, issue_number=50)


Running:
 - run_shell_command(args=['rm -rf agentmaximus-autonomous'], tail=10)


Running:
 - run_shell_command(args=['git clone https://${GITHUB_TOKEN}@github.com/AgentMaximus/autonomous.git agentmaximus-autonomous'], tail=10)


Running:
 - run_shell_command(args=['ls agentmaximus-autonomous'], tail=10)


Running:
 - read_file(file_name=agentmaximus-autonomous/fastapi_app.py)

To address issue #50, I'll integrate a background task that logs a motivational quote to the console every 10 seconds. This will involve adding a new thread dedicated to logging quotes.

### Plan

1. **Integrate Logging**:
   - Add a new function to log a motivational quote every 10 seconds.
   - Use threading to run this function concurrently with the existing data fetch.

2. **Validation**:
   - Ensure that quotes are logged at the specified interval without interfering with other tasks.

3. **Push and Document**:
   - Commit and push changes.
   - Comment on the issue with implementation details and close it.

Let's proceed by implementing these changes.
Running:
 - save_file(file_name=agentmaximus-autonomous/fastapi_app.py, contents=..., overwrite=True)


Running:
 - run_shell_command(args=['python3 agentmaximus-autonomous/fastapi_app.py'], tail=10)

The FastAPI app has been updated to include logging of motivational quotes every 10 seconds. The application should now run with the new logging feature integrated.

I will proceed to commit, push these changes to the repository, and then comment and close the related issue on GitHub.
Running:
 - run_shell_command(args=['git --git-dir=agentmaximus-autonomous/.git --work-tree=agentmaximus-autonomous add fastapi_app.py'], tail=10)


Running:
 - run_shell_command(args=["git --git-dir=agentmaximus-autonomous/.git --work-tree=agentmaximus-autonomous commit -m 'Add motivational logging every 10 seconds to application log output'"], tail=10)


Running:
 - run_shell_command(args=['git --git-dir=agentmaximus-autonomous/.git --work-tree=agentmaximus-autonomous push https://${GITHUB_TOKEN}@github.com/AgentMaximus/autonomous.git'], tail=10)


Running:
 - comment_on_issue(repo_name=AgentMaximus/autonomous, issue_number=50, comment_body=...)


Running:
 - close_issue(repo_name=AgentMaximus/autonomous, issue_number=50)

The motivational logging feature has been successfully implemented, committed, and pushed to the repository. I've added a comment on the issue explaining the changes and closed it on GitHub.

[bot]
